apiVersion: v1
kind: Service
metadata:
  name: default
  namespace: shop
  labels:
    service: default
spec:
  selector:
    service: default
  ports:
    - port: 9005
      targetPort: 9005          
  type: ClusterIP
