apiVersion: v1
kind: Service
metadata:
  name: index
  namespace: shop
  labels:
    service: index
spec:
  selector:
    service: index
  ports:
    - port: 9004
      targetPort: 9004
  type: ClusterIP
